- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed
- name: Copy Roboshop Nginx Configuration File
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf
- name: Remove Old App Content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent
- name: Create App Directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory
#- name: Download App Content and Unzip it
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
#    dest: /usr/share/nginx/html
#    remote_src: yes

- name: Download App Content and Unzip its
  ansible.builtin.unarchive:
    src: http://172.31.42.37:8081/repository/{{component}}/{{component}}-{{app_version}}.zip
    dest: /usr/share/nginx/html
    remote_src: yes
- name: Start Nginx Service
  ansible.builtin.systemd_service:
    state: restarted
    name: nginx
    daemon_reload: true
    enabled: true




