#  func_print_head "Creating Application User"
#    id ${app_user} &>>$log_file
#    if [ $? -ne 0 ]; then
#    useradd ${app_user} &>>$log_file
#    fi
#    func_stat_check $?
#    func_print_head "Creating Application Folder"
#    rm -rf /app
#    mkdir /app
#    func_stat_check $?
#    func_print_head "Downloading app content"
#    curl -L -o /tmp/${component}.zip https://roboshop-artifacts.s3.amazonaws.com/${component}.zip &>>$log_file
#    func_stat_check $?
#    cd /app
#    func_print_head "Unzip app content"
#    unzip /tmp/${component}.zip &>>$log_file
#    func_stat_check $?
- name: Add the user roboshop
  ansible.builtin.user:
    name: "{{ app_user }}"
- name: Remove Old App Content
  ansible.builtin.file:
    path: /app
    state: absent
- name: Create App Directory
  ansible.builtin.file:
    path: /app
    state: directory
#- name: Download App Content and Unzip it
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
#    dest: /app
#    remote_src: yes
- name: Download App Content and Unzip its
  ansible.builtin.unarchive:
    src: http://172.31.42.37:8081/repository/{{component}}/{{component}}-{{app_version}}.zip
    dest: /app
    remote_src: yes