#if [ "$schema_setup" == "mongo" ]
#then
#func_print_head "Copying Mongodb repo file"
#cp ${script_path}/mongo.repo /etc/yum.repos.d/mongo.repo &>>$log_file
#func_stat_check $?
#func_print_head "Downloading Mongodb"
#dnf install mongodb-org-shell -y &>>$log_file
#func_stat_check $?
#func_print_head "Load Schema"
#mongo --host mongodb-dev.kruthikadevops.online </app/schema/${component}.js &>>$log_file
#func_stat_check $?
#fi
#if [ "$schema_setup" == "mysql" ]
#then
#func_print_head "Installing Mysql client"
#dnf install mysql -y &>>$log_file
#func_stat_check $?
#func_print_head "Loading schema"
#mysql -h mysql-dev.kruthikadevops.online -uroot -p${mysql_root_password} < /app/schema/${component}.sql &>>$log_file
#func_print_head "mysql schema loaded"
#func_stat_check $?
#func_systemd
#fi

- name: Copy mongo repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo
- name: Install Mongodb client
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed
- name: Load schema
  ansible.builtin.shell: mongo --host {{ lookup('aws_ssm','dev.catalogue.mongo_endpoint', region='us-east-1') }} </app/schema/{{component}}.js
