- name: Load MongoDB Schema
  when: schema_setup == "mongo"
  block:
    - name: Copy mongo repo file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo
    - name: Install Mongodb client
      ansible.builtin.yum:
        name: mongodb-org-shell
        state: installed
    - name: Copy mongo repo file
      ansible.builtin.copy:
        src: mongosh.repo
        dest: /etc/yum.repos.d/mongosh.repo
    - name: Install Mongodb client
      ansible.builtin.yum:
        name: mongodb-mongosh
        state: installed

    - name: Download DOCDB Pem file
      ansible.builtin.get_url:
        url: https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem
        dest: /app/rds-combined-ca-bundle.pem

    - name: Load schema
      ansible.builtin.shell: mongosh {{ lookup('aws_ssm','{{ env }}.docdb.db_endpoint', region='us-east-1') }}:27017 --tls --tlsCAFile /app/rds-combined-ca-bundle.pem --retryWrites=false --username {{ lookup('aws_ssm','{{ env }}.docdb.db_user', region='us-east-1') }} --password {{ lookup('aws_ssm','{{ env }}.docdb.db_pass', region='us-east-1') }} </app/schema/{{component}}.js

- name: Load mysql Schema
  when: schema_setup == "mysql"
  block:
    - name: Install mysql client
      ansible.builtin.dnf:
        name: mysql

    - name: Load mysql schema
      ansible.builtin.shell: mysql -h {{ lookup('aws_ssm','dev.shipping.mysql_url', region='us-east-1') }} -u{{ lookup('aws_ssm','dev.{{component}}.mysql_user', region='us-east-1') }} -p{{ lookup('aws_ssm','dev.shipping.mysql_password', region='us-east-1') }} < /app/schema/{{component}}.sql

